[build]
target = "riscv64gc-unknown-none-elf"

# Linker flags. orbit-rt's build.rs emits memory.x into OUT_DIR and
# adds -L for it; -Tmemory.x picks it up.
[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-Clink-arg=-Tmemory.x",
  "-Ctarget-feature=+d",
  "-Ctarget-feature=+f"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[unstable]
build-std = ["core", "alloc"]
