[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
# Pass our executable to qemu when running `cargo run`.
#-d in_asm,int,guest_errors -S
runner = "qemu-system-riscv64 -d guest_errors -smp 4 -m 2G --trace \"memory*\" -machine virt,aclint=on -cpu max,sstc=true -bios none -serial mon:stdio -gdb tcp::1234 -netdev user,id=orbit0,net=192.168.76.0/24,dhcpstart=192.168.76.9,hostfwd=tcp::7777-:7777 -device e1000,netdev=orbit0 --trace \"e1000_*\" -global virtio-mmio.force-legacy=off -device virtio-gpu-device -display sdl,gl=off -kernel"

#[target.riscv64gc-unknown-orbit]
#linker = "rust-lld"

# Linker flags
rustflags = [
  "-Clink-arg=-Tmemory.x",
  "-Ctarget-feature=+d",
  "-Ctarget-feature=+f"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
